### ISSUE TITLE
Option to filter to dark/light themes only

### ISSUE THREAD

**Issue by joshbode** [nvllsvm/base16-shell-preview#2]
Thank you for this tool - it is very useful!

I typically only use dark themes and it would be useful to be able to provide a command-line option to only show dark (or light) themes.

**Comment by andrewrabert** [comment]
I've been thinking about this for a while and completely agree. The flashing of dark and light themes while scrolling is headache-inducing.

**Comment by joshbode** [comment]
Totally agree - the violent alternation between light and dark themes is probably what caused me to write this issue :)

I've just taken a look in the theme files and while there doesn't appear to be a general categorisation for themes to be "dark" or "light" (apart from those that are named so), it might be possible to define a cutoff on the background colour to segment into "light" and "dark".

**Comment by andrewrabert** [comment]
I've added `--sort-bg` to the master branch to sort from darkest to lightest themes.
https://github.com/nvllsvm/base16-shell-preview/commit/0e6e905e87a909c7b4f3167d4ffaf665491862a9

I'll make a new release eventually.

**Comment by joshbode** [comment]
great! I'll check it out :)

**Comment by andrewrabert** [comment]
Released in version 0.6.0
