### ISSUE TITLE
_curses.error: init_pair() returned ERR

### ISSUE THREAD

**Issue by dan-cooke** [nvllsvm/base16-shell-preview#5]
```
Traceback (most recent call last):
  File "/usr/local/bin/base16-shell-preview", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/base16_shell_preview/__main__.py", line 288, in main
    run_curses_app(scripts_dir, args.sort_bg)
  File "/usr/local/lib/python3.7/site-packages/base16_shell_preview/__main__.py", line 185, in run_curses_app
    preview_win.render()
  File "/usr/local/lib/python3.7/site-packages/base16_shell_preview/__main__.py", line 79, in render
    curses.init_pair(i, i, -1)
_curses.error: init_pair() returned ERR

```

Stopped working suddenly.

**Comment by andrewrabert** [comment]
What OS and terminal are you using and what versions are they?

**Comment by dan-cooke** [comment]
Apologies for not including in the OP.

**OS**
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G84
Darwin Kernel Version 18.7.0

**Terminal**
Alacrity 0.3.3

**Shell**
Fish 3.02

**Comment by andrewrabert** [comment]
What's the value of the `TERM` environment variable in that terminal (`echo $TERM`)? Does setting it to `xterm-256color` fix base16-shell-preview?

Some research indicates this is a common error for Python curses applications and some `TERM` values.

On my mac (macOS  10.13.6), all terminals I tested have a `TERM` value of `xterm-256color` (Terminal, iTerm, Alacritty). I'm not sure what is setting that.

---

Also, you mentioned this stopped working "suddenly". Did you upgrade anything before this happened?

**Comment by dan-cooke** [comment]
`TERM` was set to `screen` - I was installing a lot of new fish plugins at the time and I'd imagine one of them must have set this.

Setting to `xterm-256color` fixed my issue. 

Thanks for the help!

Closing
